modLoader="javafml"
loaderVersion="[52,)"
license="Apache-2.0"
[[mods]]
modId="loaderbridge_fabric_registry_sync_v0"
version="5.1.3.5"
displayName="LoaderBridge Fabric Registry Sync v0 Bridge"
[[dependencies.loaderbridge_fabric_registry_sync_v0]]
modId="forge"
mandatory=true
versionRange="[52.1.0,53)"
ordering="NONE"
side="BOTH"
