modLoader="javafml"
loaderVersion="[52,)"
license="Apache-2.0"

[[mods]]
modId="loaderbridge_fabric_item_api_v1"
version="11.3.0.4"
displayName="LoaderBridge Fabric Item API v1 Bridge"

[[dependencies.loaderbridge_fabric_item_api_v1]]
modId="forge"
mandatory=true
versionRange="[52.1.0,53)"
ordering="NONE"
side="BOTH"
