modLoader="javafml"
loaderVersion="[52,)"
license="Apache-2.0"

[[mods]]
modId="loaderbridge_fabric_data_attachment_api_v1"
version="1.4.7.6"
displayName="LoaderBridge Fabric Data Attachment API v1 Bridge"

[[dependencies.loaderbridge_fabric_data_attachment_api_v1]]
modId="forge"
mandatory=true
versionRange="[52.1.0,53)"
ordering="NONE"
side="BOTH"
