modLoader="javafml"
loaderVersion="[52,)"
license="Apache-2.0"

[[mods]]
modId="loaderbridge_fabric_recipe_api_v1"
version="5.0.16.1"
displayName="LoaderBridge Fabric Recipe API v1 Bridge"

[[dependencies.loaderbridge_fabric_recipe_api_v1]]
modId="forge"
mandatory=true
versionRange="[52.1.0,53)"
ordering="NONE"
side="BOTH"
