plugins { id 'net.minecraftforge.gradle' version '6.0.54' }

minecraft { mappings channel: 'official', version: '1.21.1'; reobf = false }

repositories {
    exclusiveContent {
        forRepository { maven { url = 'https://libraries.minecraft.net/' } }
        filter { includeGroup 'org.lwjgl' }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.21.1-52.1.0'
    implementation project(':bridge-api')
    implementation(project(':fabric-api-base-bridge')) { transitive = false }
}

tasks.named('jar') {
    manifest {
        attributes('Automatic-Module-Name': 'dev.loaderbridge.fabric.registry.sync',
                'LICENSE': 'Apache-2.0',
                'Implementation-Version': '5.1.3+60c3209b19-loaderbridge.1',
                'MixinConfigs': 'loaderbridge.fabric-registry-sync.mixins.json')
    }
}
