plugins { id 'net.minecraftforge.gradle' version '6.0.54' }

minecraft { mappings channel: 'official', version: '1.21.1'; reobf = false }

repositories {
    exclusiveContent {
        forRepository { maven { url = 'https://libraries.minecraft.net/' } }
        filter { includeGroup 'org.lwjgl' }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.21.1-52.1.0'
    implementation project(':bridge-api')
}

tasks.named('jar') {
    manifest {
        attributes('Automatic-Module-Name': 'dev.loaderbridge.fabric.api.object.builder',
                'LICENSE': 'Apache-2.0',
                'Implementation-Version': '15.2.1+40875a9319-loaderbridge.8',
                'MixinConfigs': 'loaderbridge.fabric-object-builder.mixins.json')
    }
}
