package dev.loaderbridge.fabric.api.object.builder.mixin;

import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.ToIntFunction;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.flag.FeatureFlagSet;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;

/** Field-level copy surface for FabricBlockSettings' pinned deep-copy behavior. */
@Mixin(BlockBehaviour.Properties.class)
public interface BlockBehaviourPropertiesAccessor {
    @Accessor("mapColor") Function<BlockState, MapColor> loaderbridge$getMapColor();
    @Accessor("mapColor") void loaderbridge$setMapColor(Function<BlockState, MapColor> value);
    @Accessor("hasCollision") boolean loaderbridge$getHasCollision();
    @Accessor("hasCollision") void loaderbridge$setHasCollision(boolean value);
    @Accessor("soundType") SoundType loaderbridge$getSoundType();
    @Accessor("soundType") void loaderbridge$setSoundType(SoundType value);
    @Accessor("lightEmission") ToIntFunction<BlockState> loaderbridge$getLightEmission();
    @Accessor("lightEmission") void loaderbridge$setLightEmission(ToIntFunction<BlockState> value);
    @Accessor("explosionResistance") float loaderbridge$getExplosionResistance();
    @Accessor("explosionResistance") void loaderbridge$setExplosionResistance(float value);
    @Accessor("destroyTime") float loaderbridge$getDestroyTime();
    @Accessor("destroyTime") void loaderbridge$setDestroyTime(float value);
    @Accessor("requiresCorrectToolForDrops") boolean loaderbridge$getRequiresCorrectToolForDrops();
    @Accessor("requiresCorrectToolForDrops") void loaderbridge$setRequiresCorrectToolForDrops(boolean value);
    @Accessor("isRandomlyTicking") boolean loaderbridge$getIsRandomlyTicking();
    @Accessor("isRandomlyTicking") void loaderbridge$setIsRandomlyTicking(boolean value);
    @Accessor("friction") float loaderbridge$getFriction();
    @Accessor("friction") void loaderbridge$setFriction(float value);
    @Accessor("speedFactor") float loaderbridge$getSpeedFactor();
    @Accessor("speedFactor") void loaderbridge$setSpeedFactor(float value);
    @Accessor("jumpFactor") float loaderbridge$getJumpFactor();
    @Accessor("jumpFactor") void loaderbridge$setJumpFactor(float value);
    @Accessor("drops") ResourceKey<LootTable> loaderbridge$getDrops();
    @Accessor("drops") void loaderbridge$setDrops(ResourceKey<LootTable> value);
    @Accessor("canOcclude") boolean loaderbridge$getCanOcclude();
    @Accessor("canOcclude") void loaderbridge$setCanOcclude(boolean value);
    @Accessor("isAir") boolean loaderbridge$getIsAir();
    @Accessor("isAir") void loaderbridge$setIsAir(boolean value);
    @Accessor("ignitedByLava") boolean loaderbridge$getIgnitedByLava();
    @Accessor("ignitedByLava") void loaderbridge$setIgnitedByLava(boolean value);
    @Accessor("liquid") boolean loaderbridge$getLiquid();
    @Accessor("liquid") void loaderbridge$setLiquid(boolean value);
    @Accessor("forceSolidOff") boolean loaderbridge$getForceSolidOff();
    @Accessor("forceSolidOff") void loaderbridge$setForceSolidOff(boolean value);
    @Accessor("forceSolidOn") boolean loaderbridge$getForceSolidOn();
    @Accessor("forceSolidOn") void loaderbridge$setForceSolidOn(boolean value);
    @Accessor("pushReaction") PushReaction loaderbridge$getPushReaction();
    @Accessor("pushReaction") void loaderbridge$setPushReaction(PushReaction value);
    @Accessor("spawnTerrainParticles") boolean loaderbridge$getSpawnTerrainParticles();
    @Accessor("spawnTerrainParticles") void loaderbridge$setSpawnTerrainParticles(boolean value);
    @Accessor("instrument") NoteBlockInstrument loaderbridge$getInstrument();
    @Accessor("instrument") void loaderbridge$setInstrument(NoteBlockInstrument value);
    @Accessor("replaceable") boolean loaderbridge$getReplaceable();
    @Accessor("replaceable") void loaderbridge$setReplaceable(boolean value);
    @Accessor("lootTableSupplier") Supplier<ResourceKey<LootTable>> loaderbridge$getLootTableSupplier();
    @Accessor("lootTableSupplier") void loaderbridge$setLootTableSupplier(Supplier<ResourceKey<LootTable>> value);
    @Accessor("isValidSpawn") BlockBehaviour.StateArgumentPredicate<EntityType<?>> loaderbridge$getIsValidSpawn();
    @Accessor("isValidSpawn") void loaderbridge$setIsValidSpawn(BlockBehaviour.StateArgumentPredicate<EntityType<?>> value);
    @Accessor("isRedstoneConductor") BlockBehaviour.StatePredicate loaderbridge$getIsRedstoneConductor();
    @Accessor("isRedstoneConductor") void loaderbridge$setIsRedstoneConductor(BlockBehaviour.StatePredicate value);
    @Accessor("isSuffocating") BlockBehaviour.StatePredicate loaderbridge$getIsSuffocating();
    @Accessor("isSuffocating") void loaderbridge$setIsSuffocating(BlockBehaviour.StatePredicate value);
    @Accessor("isViewBlocking") BlockBehaviour.StatePredicate loaderbridge$getIsViewBlocking();
    @Accessor("isViewBlocking") void loaderbridge$setIsViewBlocking(BlockBehaviour.StatePredicate value);
    @Accessor("hasPostProcess") BlockBehaviour.StatePredicate loaderbridge$getHasPostProcess();
    @Accessor("hasPostProcess") void loaderbridge$setHasPostProcess(BlockBehaviour.StatePredicate value);
    @Accessor("emissiveRendering") BlockBehaviour.StatePredicate loaderbridge$getEmissiveRendering();
    @Accessor("emissiveRendering") void loaderbridge$setEmissiveRendering(BlockBehaviour.StatePredicate value);
    @Accessor("dynamicShape") boolean loaderbridge$getDynamicShape();
    @Accessor("dynamicShape") void loaderbridge$setDynamicShape(boolean value);
    @Accessor("requiredFeatures") FeatureFlagSet loaderbridge$getRequiredFeatures();
    @Accessor("requiredFeatures") void loaderbridge$setRequiredFeatures(FeatureFlagSet value);
    @Accessor("offsetFunction") BlockBehaviour.OffsetFunction loaderbridge$getOffsetFunction();
    @Accessor("offsetFunction") void loaderbridge$setOffsetFunction(BlockBehaviour.OffsetFunction value);
}
