modLoader="javafml"
loaderVersion="[52,)"
license="Apache-2.0"

[[mods]]
modId="loaderbridge_fabric_lifecycle"
version="2.6.0.3"
displayName="LoaderBridge Fabric Lifecycle Events Bridge"

[[dependencies.loaderbridge_fabric_lifecycle]]
modId="forge"
mandatory=true
versionRange="[52.1.0,53)"
ordering="NONE"
side="BOTH"
